services:
  postgres:
    image: postgres:latest
    ports:
      - "8888:5432"
    environment:
      - POSTGRES_DB=optimalpacking
      - POSTGRES_USER=optimalpacking-user
      - POSTGRES_PASSWORD=123456