services:
  postgres:
    image: postgres:latest
    ports:
      - "8889:5432"
    environment:
      - POSTGRES_DB=optimalpacking-billing
      - POSTGRES_USER=optimalpacking-billing-user
      - POSTGRES_PASSWORD=123456